source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'KNHelp' do
pod 'AFNetworking', '~> 3.0'
pod 'FMDB'
pod 'SDWebImage', '~>3.8'
pod 'JSONModel'
pod 'CocoaLumberjack'
pod 'JKCategories'
pod 'MJRefresh'
pod 'LCTabBarController'
pod 'SVProgressHUD'
pod 'YTKKeyValueStore'
pod 'IQKeyboardManager'
pod 'XHTextField'
pod 'NetworkEye', '~> 1.0.6'
pod 'DZNEmptyDataSet'
pod 'CocoaAsyncSocket'
pod 'RealReachability'
pod 'DZNEmptyDataSet'
end
